name: Package and Upload to CodeArtifact

on:
  push:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --user build

      - name: Build package
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 3

  publish-to-codeartifact:
    name: Publish Python distribution to CodeArtifact
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') # タグがvで始まる場合のみ実行
    needs:
      - build
    permissions:
      id-token: write # OIDC認証に必要

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-CodeArtifact

      - name: Get CodeArtifact authorization token
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} \
            --query authorizationToken \
            --output text)
          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Get CodeArtifact repository endpoint
        run: |
          CODEARTIFACT_REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} \
            --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} \
            --format pypi \
            --query repositoryEndpoint \
            --output text)
          echo "::add-mask::$CODEARTIFACT_REPO_URL"
          echo "CODEARTIFACT_REPO_URL=$CODEARTIFACT_REPO_URL" >> $GITHUB_ENV

      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to CodeArtifact
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: aws
          password: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          repository-url: ${{ env.CODEARTIFACT_REPO_URL }}
          attestations: false
